Task06_Akhmetyanov
EgorkaKulikov/spbu-se2019-autumn pull request #106
Opened 2019-12-14 17:22 UTC by azaat

Measure time with: nvcc measure_time.cu bitonic_sort_gpu.cu bitonic_sort.cu -o measure_time && measure_time
Test with:  nvcc test.cu bitonic_sort_gpu.cu bitonic_sort.cu -o test && test

2019-12-15 19:04 UTC, NikitaMishin commented on Task06/bitonic_sort_gpu.cu
> +			bitonic_sort_step <<< num_blocks, num_threads >>> (gpu_arr, comp_dist, seq_size);
а не пробовали все на гпу перенести? А то тут очеь много накладгных расходов получается?

2019-12-15 19:06 UTC, NikitaMishin commented
компилировали с -O3?

2019-12-15 19:08 UTC, azaat commented on Task06/bitonic_sort_gpu.cu
> +			bitonic_sort_step <<< num_blocks, num_threads >>> (gpu_arr, comp_dist, seq_size);
Два внешних цикла по логарифму, так что не так уж и много

2019-12-15 19:10 UTC, NikitaMishin commented on Task06/bitonic_sort_gpu.cu
> +			bitonic_sort_step <<< num_blocks, num_threads >>> (gpu_arr, comp_dist, seq_size);
я к тому, что запуск кернелов дорогая операция... Хотя, в данном случае, наверное, малый влкад во время вносит --- надо на профилятор смотреть))))))

2019-12-15 19:11 UTC, azaat commented
> 
> 
> компилировали с -O3?
Нет, с теми же опциями, что указаны сверху в описании

2019-12-17 12:49 UTC, NikitaMishin requested changes

2019-12-17 12:49 UTC, NikitaMishin commented on Task06/measure_time.cu
> +			cpu_exec_time += get_exec_time(start, clock()) / NUM_MEASUREMENTS;
а не лучше ли делить в конце на num_measurements(после цикла)?   при большом количестве измерений  уу нас всегда будет ноль при.

2019-12-17 13:08 UTC, azaat commented on Task06/measure_time.cu
> +			cpu_exec_time += get_exec_time(start, clock()) / NUM_MEASUREMENTS;
Да, неудачное решение, исправил

2019-12-17 13:21 UTC, NikitaMishin approved these changes

2019-12-17 21:28 UTC, merged