Task06_Gamaonov
EgorkaKulikov/spbu-se2019-autumn pull request #108
Opened 2019-12-15 03:46 UTC by AlanGamaonov

Не знаю, нужно ли было реализовывать все 3 алгоритма, но мне показалось, что формулировка предполагает один.
![viterbi](https://user-images.githubusercontent.com/42998371/70857801-7ae03400-1f06-11ea-8ef3-a51d71c04222.png)

2019-12-15 18:12 UTC, NikitaMishin commented
да, один такая была формулировка, все верно

2019-12-15 18:37 UTC, NikitaMishin commented on kernel.cu
> +	//� �������������� �� �������� ������� �������
содержательные комментарии)))))

2019-12-15 18:44 UTC, NikitaMishin commented on kernel.cu
> +	cudaMemcpy(temp, deviceMatrix, ROWS_NUM * COLUMN_NUM * sizeof(double), cudaMemcpyDeviceToHost);
вызовы еще надо проверять на корректность, добавьте gpuAssert(https://stackoverflow.com/questions/14038589/what-is-the-canonical-way-to-check-for-errors-using-the-cuda-runtime-api)

2019-12-15 18:51 UTC, NikitaMishin reviewed
C виду все ок, код уже сегодня не успею запустить, но все нравится. Не пробовали запускать на больших данных? Интересно посмотреть на динамику

2019-12-15 19:24 UTC, AlanGamaonov commented on kernel.cu
> +	//� �������������� �� �������� ������� �������
Отвратительно... 🤦‍♂️

2019-12-17 13:29 UTC, NikitaMishin requested changes
Хммм, тут как раз не помешает GPUASSErt, чтобы понять, где дампистся(пробовал и с 11 стандартом тоже) Запускал на 300 , поэтому памяти должно было хватить
![Screenshot from 2019-12-17 16-26-40](https://user-images.githubusercontent.com/22191229/70999365-5a70cf00-20ea-11ea-9d24-30743d8ea4c5.png)

2019-12-18 16:57 UTC, AlanGamaonov commented
> Хммм, тут как раз не помешает GPUASSErt, чтобы понять, где дампистся(пробовал и с 11 стандартом тоже) Запускал на 300 , поэтому памяти должно было хватить
> ![Screenshot from 2019-12-17 16-26-40](https://user-images.githubusercontent.com/22191229/70999365-5a70cf00-20ea-11ea-9d24-30743d8ea4c5.png)

В общем, есть вопросы. Скинул одногруппнику код, у него тоже ошибки при компиляции, но на моей машине проблема не воспроизводится. Если посмотреть на значения внутри MIndex, вот что выводится у него:
![bhICf6B5bzs](https://user-images.githubusercontent.com/42998371/71106278-21128f00-21d0-11ea-9ff3-dbb492021bd6.jpg)

А вот у меня:
![hRyHZtDMxR0](https://user-images.githubusercontent.com/42998371/71106331-3daec700-21d0-11ea-9fa7-a058e9f96d93.jpg)

Оба на, винде, если что

2019-12-18 17:10 UTC, NikitaMishin commented
> > Хммм, тут как раз не помешает GPUASSErt, чтобы понять, где дампистся(пробовал и с 11 стандартом тоже) Запускал на 300 , поэтому памяти должно было хватить
> > ![Screenshot from 2019-12-17 16-26-40](https://user-images.githubusercontent.com/22191229/70999365-5a70cf00-20ea-11ea-9d24-30743d8ea4c5.png)
> 
> В общем, есть вопросы. Скинул одногруппнику код, у него тоже ошибки при компиляции, но на моей машине проблема не воспроизводится. Если посмотреть на значения внутри MIndex, вот что выводится у него:
> ![bhICf6B5bzs](https://user-images.githubusercontent.com/42998371/71106278-21128f00-21d0-11ea-9ff3-dbb492021bd6.jpg)
> 
> А вот у меня:
> ![hRyHZtDMxR0](https://user-images.githubusercontent.com/42998371/71106331-3daec700-21d0-11ea-9fa7-a058e9f96d93.jpg)
> 
> Оба на, винде, если что

А какая версия куда?

2019-12-18 17:13 UTC, AlanGamaonov commented
> > > Хммм, тут как раз не помешает GPUASSErt, чтобы понять, где дампистся(пробовал и с 11 стандартом тоже) Запускал на 300 , поэтому памяти должно было хватить
> > > ![Screenshot from 2019-12-17 16-26-40](https://user-images.githubusercontent.com/22191229/70999365-5a70cf00-20ea-11ea-9d24-30743d8ea4c5.png)
> > 
> > 
> > В общем, есть вопросы. Скинул одногруппнику код, у него тоже ошибки при компиляции, но на моей машине проблема не воспроизводится. Если посмотреть на значения внутри MIndex, вот что выводится у него:
> > ![bhICf6B5bzs](https://user-images.githubusercontent.com/42998371/71106278-21128f00-21d0-11ea-9ff3-dbb492021bd6.jpg)
> > А вот у меня:
> > ![hRyHZtDMxR0](https://user-images.githubusercontent.com/42998371/71106331-3daec700-21d0-11ea-9fa7-a058e9f96d93.jpg)
> > Оба на, винде, если что
> 
> А какая версия куда?
10.2
Только вот эта ошибка возникает ещё в последовательной версии алгоритма

2019-12-18 17:17 UTC, NikitaMishin commented
> > > > Хммм, тут как раз не помешает GPUASSErt, чтобы понять, где дампистся(пробовал и с 11 стандартом тоже) Запускал на 300 , поэтому памяти должно было хватить
> > > > ![Screenshot from 2019-12-17 16-26-40](https://user-images.githubusercontent.com/22191229/70999365-5a70cf00-20ea-11ea-9d24-30743d8ea4c5.png)
> > > 
> > > 
> > > В общем, есть вопросы. Скинул одногруппнику код, у него тоже ошибки при компиляции, но на моей машине проблема не воспроизводится. Если посмотреть на значения внутри MIndex, вот что выводится у него:
> > > ![bhICf6B5bzs](https://user-images.githubusercontent.com/42998371/71106278-21128f00-21d0-11ea-9ff3-dbb492021bd6.jpg)
> > > А вот у меня:
> > > ![hRyHZtDMxR0](https://user-images.githubusercontent.com/42998371/71106331-3daec700-21d0-11ea-9fa7-a058e9f96d93.jpg)
> > > Оба на, винде, если что
> > 
> > 
> > А какая версия куда?
> > 10.2
> > Только вот эта ошибка возникает ещё в последовательной версии алгоритма

Тогда , получается, проблемы с доступом к памяти на хосте, где-то кто-то лезет в память не по адресу. Мб еще разные компиляторы влияют. Но в любом случае баг))

2019-12-18 22:00 UTC, merged