Task04_Gordienko
EgorkaKulikov/spbu-se2019-autumn pull request #17
Opened 2019-10-27 20:45 UTC by GordienkoEgor

Initial implementation of task 04.

2019-11-03 11:35 UTC, EgorkaKulikov requested changes

2019-11-03 11:35 UTC, EgorkaKulikov commented on Task04/Program.cs
> +            MainAsync(inputUrl);
Мне кажется, тут неплохо написано про запуск async из main
https://stackoverflow.com/questions/9208921/cant-specify-the-async-modifier-on-the-main-method-of-a-console-app

2019-11-03 11:35 UTC, EgorkaKulikov commented on Task04/Program.cs
> +        static async Task MainAsync(string inputUrl)
Предлагаю вынести всю эту логику в отдельный класс вместо повсеместного использования статики, а также не забывать нигде модификаторы доступа.

2019-11-03 11:35 UTC, EgorkaKulikov commented on Task04/Program.cs
> +            MainAsync(inputUrl);
Я это даже в чатик вкинул.

2019-11-03 11:35 UTC, EgorkaKulikov commented on Task04/Program.cs
> +        {
Лучше так 
string message = size == -1 ? ... : ...
Console.WriteLine(message);

2019-11-03 11:35 UTC, EgorkaKulikov commented on Task04/Program.cs
> +            return urlContent.Length;
А нельзя ли написать 
return urlContent?.Length ?? -1;

2019-11-03 11:35 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                //keep urlContent null
В catch-блоке нужно сделать хоть что-то. Залоггировать, например. Но не просто замаскировать проблему.

2019-11-18 19:34 UTC, GordienkoEgor commented
Поправил замечания

2019-11-24 18:23 UTC, merged