Task04_Akhmetyanov
EgorkaKulikov/spbu-se2019-autumn pull request #30
Opened 2019-10-31 10:31 UTC by azaat

2019-11-24 19:08 UTC, EgorkaKulikov requested changes

2019-11-24 19:08 UTC, EgorkaKulikov commented on Task04/WebAsync.cs
> +    public class WebAsync
Странное имя класса

2019-11-24 19:08 UTC, EgorkaKulikov commented on Task04/WebAsync.cs
> +        public string PageData { get; private set; } = "";
Это MainPageData ?

2019-11-24 19:08 UTC, EgorkaKulikov commented on Task04/WebAsync.cs
> +                PageLoaded = true;
не вполне понял назначения этой переменной

2019-11-24 19:08 UTC, EgorkaKulikov commented on Task04/WebAsync.cs
> +                Console.WriteLine("Unable to load http request, uri: {0}"
вкусовщина, но я бы три буквы не переносил на новую строку
опционально

2019-11-24 19:08 UTC, EgorkaKulikov commented on Task04/Program.cs
> +            WebAsync webAsyncClient = new WebAsync();
var

2019-11-24 19:08 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                    //Client for sub urls
кажется, при адекватном имени класса комментарий сразу не нужен станет

2019-11-27 12:44 UTC, azaat commented on Task04/WebAsync.cs
> +    public class WebAsync
Поменял на PageLoader, думаю так понятнее

2019-11-27 12:48 UTC, azaat commented on Task04/WebAsync.cs
> +                PageLoaded = true;
Это побочный эффект того, что часть логики была в main, уже перенес загрузку подстраниц в PageLoader и эта переменная не нужна

2019-11-30 10:11 UTC, merged