Task02_Sukhanova
EgorkaKulikov/spbu-se2019-autumn pull request #37
Opened 2019-10-31 17:53 UTC by AnzhelaSukhanova

2019-11-03 14:52 UTC, EgorkaKulikov requested changes

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Floyd.cs
> +        {
То, что здесь происходит, напоминает смешение конструктора, но только не матрицы смежности, а графа в целом, и обработки входных данных. Такие вещи явно нужно разделить.

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Floyd.cs
> +        private int N = 0;
Однобуквенные переменные за исключением переменных цикла и ещё очень редких случаев не используем.

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Floyd.cs
> +                th.Join();
Вообще можно вместо кучи Join один WaitHandle написать
https://stackoverflow.com/questions/4190949/create-multiple-threads-and-wait-all-of-them-to-complete

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Floyd.cs
> +        private void OneThreadFloyd(Object ver)
Функция есть действие, значит название должно содержать глагол.

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Floyd.cs
> +            int k = (int)ver;
Зачем передавтаь object, чтобы первым же действием приводить его к int
А если не приведётся?

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Kruskal.cs
> +        {
Вообще, мне кажется, для всех задач нужен единый Graph и единый его конструктор. Ну или производные от базового.

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Kruskal.cs
> +        {
Ну и просто правило: ввод/вывод - отдельно, логика - отдельно

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Kruskal.cs
> +                        if (graph[graph.Count - 1][2] < w) graph.Add(new int[] {i, j, w});
а что это за элемент [2], Какой у него смысл? Может быть, нужно завести структуру/кортеж и обращатсья по имени?

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Kruskal.cs
> +                th.Start(k);
Кажется, мы уже второй раз делаем параллелизма на потоках, а договаривались использовать каждую технологию по разу.

2019-11-03 14:52 UTC, EgorkaKulikov commented on Task02/Prim.cs
> +        {
Не увидел алгоритма, основанного на тасках

2019-11-03 21:15 UTC, AnzhelaSukhanova commented on Task02/Floyd.cs
> +            int k = (int)ver;
ParameterizedThreadStart требует object

2019-11-03 21:26 UTC, AnzhelaSukhanova commented on Task02/Kruskal.cs
> +        {
Так изначально и задумывалось :) Но граф для алгоритма Краскала неудобно представлять так же, как для остальных алгоритмов

2019-11-03 21:29 UTC, AnzhelaSukhanova commented on Task02/Prim.cs
> +        {
Я, вроде, почти всё исправила (кроме тех пунктов, которые прокомментировала)

2019-11-24 19:20 UTC, EgorkaKulikov commented on Task02/Floyd.cs
> +        {
Кажется, вопрос остаётся актуальным

2019-11-25 09:16 UTC, AnzhelaSukhanova commented on Task02/Floyd.cs
> +        {
В условии задачи явно сказано, каким образом представлены входные данные: почему плохо конструировать граф непосредственно по ним?

2019-11-30 10:14 UTC, EgorkaKulikov commented
@AnzhelaSukhanova этот пулреквест сделан не в личную ветку, а в мастер. Поэтому его нужно закрыть и сделать новый с тем же самым кодом, но только в свою ветку. К сожалению, в первой задаче я уже пропустил этот момент. Надо также сделать пулреквест, который уберёт всё, что тогда было выложено в мастер, и переложит тот код в личную папку.

2019-11-30 20:13 UTC, closed without merging