Task04_Sukhanova
EgorkaKulikov/spbu-se2019-autumn pull request #59
Opened 2019-11-14 19:45 UTC by AnzhelaSukhanova

2019-11-24 19:44 UTC, EgorkaKulikov requested changes

2019-11-24 19:44 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                    string link = matches[i].Value.Substring(9, matches[i].Value.Length - 11);
выглядит магией

2019-11-24 19:44 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                    WebClient client = new WebClient();
var
потому что понятно, что в правой части

2019-11-24 19:44 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                WebClient client = new WebClient ();
странные пробелы перед скобками

2019-11-24 19:44 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                Task task = pr.DownloadPages();
так а почему не просто await? зачем разворачивать в две строки?

2019-11-24 19:44 UTC, EgorkaKulikov commented on Task04/Program.cs
> +                Program pr = new Program();
вот это очень странно

2019-11-24 19:44 UTC, EgorkaKulikov commented on Task04/Program.cs
> +            for (int i = 0; i < matches.Count; i++)
а почему не foreach?

2019-11-25 07:17 UTC, AnzhelaSukhanova commented on Task04/Program.cs
> +                    string link = matches[i].Value.Substring(9, matches[i].Value.Length - 11);
Здесь я отрезаю от строки ссылки кусочки <a href=" и "> просто для "красивого" вывода

2019-11-25 07:24 UTC, AnzhelaSukhanova commented on Task04/Program.cs
> +            for (int i = 0; i < matches.Count; i++)
Использую индекс для именования скачанных веб-страниц

2019-11-25 07:47 UTC, AnzhelaSukhanova commented on Task04/Program.cs
> +            for (int i = 0; i < matches.Count; i++)
Постаралась исправить недочёты: можно смотреть :)

2019-11-30 10:20 UTC, merged