Task05_Sukhanova
EgorkaKulikov/spbu-se2019-autumn pull request #79
Opened 2019-12-04 19:09 UTC by AnzhelaSukhanova

2019-12-15 03:10 UTC, AnzhelaSukhanova commented
С профилированием возникли некоторые сложности. Мне очень хотелось профилировать именно в ubuntu, потому что я в ней обычно пишу, и мне так было бы удобнее и привычнее. Оказалось, что это была не лучшая мысль. В идеале было бы профилировать прямо внутри rider, и, вроде, у него должен быть встроенный dotTrace, но попытки его найти успехом не увенчались. Поставить dotTrace отдельно тоже не получилось. Тогда я попыталась установить другой профилятор (ещё на паре мне понравился perf), и он даже пытался работать, но флэмграфы, которые я получила, выглядели максимально не наглядно. На все эти метания у меня ушло больше суток, так что мне, расстроенной и уставшей, пришлось профилировать свой код в dotTrace на windows. Если бы я это сделала сразу, то дополнила бы результаты профилирования собственным вдумчивым анализом, но всё случилось именно так, как случилось, поэтому пока его нет. Постараюсь сделать. 

P. S. Почему именно dotTrace? Всё просто: мы делали по нему доклад, так что он уже стоял на windows + я имела о нём какое-то представление

2019-12-15 15:43 UTC, NikitaMishin commented
как посмотреть .dtp файлы ?(для незнающих)

2019-12-15 15:54 UTC, NikitaMishin commented
А вы тестили?)
![Screenshot from 2019-12-15 18-53-23](https://user-images.githubusercontent.com/22191229/70865256-561ea780-1f6c-11ea-8219-e77d15d82206.png)

2019-12-15 16:16 UTC, NikitaMishin requested changes
Ну, версия с тремя мьютексами у меня не смогла закончиться ((((
Версия с Fine иногда падает

2019-12-15 16:16 UTC, NikitaMishin commented on Task05/Coarse.cs
> +            public BinaryTreeNode left;
за именование душить не буду, но есть соглашения по именованию https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members )

2019-12-15 16:16 UTC, NikitaMishin commented on Task05/Fine.cs
> +            public Mutex mutex;
почему public? У нас тогда у пользователя есть доступ к нему, а это очень нехорошо. Мы наоборот. детали реализации хотим скрыть.Верно?

2019-12-15 16:16 UTC, NikitaMishin commented on Task05/Fine.cs
> +        private Mutex firstCameMutex = new Mutex();
Вот тут как раз у вас private, что надо

2019-12-15 16:16 UTC, NikitaMishin commented on Task05/Fine.cs
> +                    BinaryTreeNode result = Find(value, ref thisNode.left);
а мы можем быть уверены, что после отпускания мьютекса в этой строчке не будет null у левого предка?

2019-12-15 16:24 UTC, NikitaMishin commented
И где тесты основных сценариев?

2019-12-15 17:10 UTC, AnzhelaSukhanova commented on Task05/Coarse.cs
> +            public BinaryTreeNode left;
Ок, спасибо, поработаю над этим

2019-12-15 17:19 UTC, AnzhelaSukhanova commented
Тесты в папке Tests (tree0 - вырожденное дерево; tree1, tree2 - более-менее сбалансированные варианты; tree3 - просто большое)
Fine падает на вырожденном варианте? Тестила, но видимо, недостаточно: сейчас посмотрю
Снимки не открываются в dotTrace? Возможно, я не все файлы залила, но у меня открывалось

2019-12-15 18:17 UTC, AnzhelaSukhanova commented
Fine действительно иногда падает в Insert() на вырожденных деревьях. Спасибо, что заметили. Реализация удаления была необязательна: я попробую успеть исправить эту проблему до зачёта, но в крайнем случае займусь ей чуть позже

2019-12-15 18:37 UTC, AnzhelaSukhanova commented on Task05/Fine.cs
> +            public Mutex mutex;
Да, но Insert, Remove и Find тоже должны иметь доступ к этим полям

2019-12-15 19:19 UTC, NikitaMishin commented on Task05/Fine.cs
> +            public Mutex mutex;
а интернал не исправит ситуацию?

2019-12-15 19:22 UTC, NikitaMishin commented
ну я имел в виду нормальные тесты )) Как у остальныХ)

2019-12-15 21:18 UTC, AnzhelaSukhanova commented on Task05/Fine.cs
> +            public Mutex mutex;
Да, я просто думала, что есть желание запретить доступ в этой же сборке тоже (сейчас залью исправленный вариант)

2019-12-15 21:26 UTC, AnzhelaSukhanova commented
Вроде, изначально речь шла о просто тестах :(

2019-12-16 22:17 UTC, EgorkaKulikov commented
@NikitaMishin какой тут статус? что ещё ждём?

2019-12-17 19:21 UTC, NikitaMishin commented
ок

2019-12-17 19:21 UTC, NikitaMishin approved these changes

2019-12-17 21:17 UTC, merged