Task02_Smirnov
EgorkaKulikov/spbu-se2019-autumn pull request #8
Opened 2019-10-19 13:11 UTC by SmirnovOleg

2019-11-03 11:07 UTC, EgorkaKulikov requested changes

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/.idea/.idea.Task02/.idea/contentModel.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ой, а зачем всякие такие вещи приехали в пулреквест?

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/.idea/.idea.Task02/.idea/contentModel.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Мне кажется, тут много лишних файлов

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/Task02/Edges.cs
> +            return HashCode.Combine(FirstVertex, SecondVertex);
Не уверен, что такое решение будет удачным в боевом приложении. Я бы посмотрел, например, как Решарпер предлагает в такой ситуации хэш-код генерировать.

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/Task02/Edges.cs
> +            return HashCode.Combine(FirstVertex, SecondVertex);
Equals, кстати, тоже я бы там посмотрел. Не знаю, зачем здесь две строчки логики размазаны на два метода.

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/Task02/ParallelAlgorithms.cs
> +    public static class ParallelAlgorithms
А почему этот класс статический? Разве в двух разных концах большого приложения не могут захотеть одновременно запустить алгоритм поиска остовного дерева? И тогда в статическом классе они начнут ещё и гоняться друг с другом.

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/Task02/Program.cs
> +                {
Помню вопрос на эту тему. Мне кажется, в данному случае, когда очень чётко понятно, какая именно треть логики try блока может выбросить FileNotFoundException и более-менее только его, я бы вынес эту логику за его пределы и там добавил проверку, что если файл не нашёлся, то нужно выбросить исключение.

2019-11-03 11:07 UTC, EgorkaKulikov commented on Task02/Task02/ParallelAlgorithms.cs
> +    public static class ParallelAlgorithms
Кажется, в этом решении вообще очень много лишней статики.

2019-11-03 13:55 UTC, viabzalov commented on Task02/Task02/Utils.cs
> +                while (graph[u, v = random.Next(n)] != 0 || v == u) {}
Можно более лаконично:
`u = random.Next(0, n - 1); v = random.Next(u + 1, n);`

2019-11-08 19:57 UTC, SmirnovOleg commented on Task02/.idea/.idea.Task02/.idea/contentModel.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ну, .gitignore я брал из официального репо райдера, и подумал, что эти файлы нужны для сборки. Но если так, пусть останутся только *.cs

2019-11-08 20:05 UTC, SmirnovOleg commented on Task02/Task02/Edges.cs
> +            return HashCode.Combine(FirstVertex, SecondVertex);
В Решарпер [посмотрел](https://www.jetbrains.com/help/resharper/Code_Generation__Equality_Members.html) - Equals() сделано почти так же, двумя методами, но элегантнее, исправил. Про hashcode мне понравился ответ Jon Skeet [здесь](https://stackoverflow.com/a/1646913), сделал так же.

2019-11-08 20:08 UTC, SmirnovOleg commented on Task02/Task02/ParallelAlgorithms.cs
> +    public static class ParallelAlgorithms
Вот тут вопрос: как нас спасет от гонок удаление static? Если мы будем вызывать эти методы из разных потоков, гонка будет хоть как, ибо идет обращение к одним данным - графу. В том же потоке - код не пойдет исполняться дальше, пока не завершится выполнение этого метода, значит здесь проблемы нет. Ну и выходит, что спастись от гонок совсем мы не можем, все таки, это уже задача юзера, который имплементит себе эти алгоритмы. Или я все-таки неправильно понял проблему?)

2019-11-08 20:14 UTC, SmirnovOleg commented on Task02/Task02/ParallelAlgorithms.cs
> +    public static class ParallelAlgorithms
Про static в целом - он тут везде навешен на алгоритмы, мне показалось это логичным в контексте данной системы классов. Какой-нибудь Array.sort() в Java тоже статичный, почему здесь нет?

2019-11-08 20:24 UTC, SmirnovOleg commented on Task02/Task02/Program.cs
> +                {
Да, но тут проблема с другим - от того, как отработает считывание графа зависит, стоит ли запускать все алгоритмы далее. Т.е. если поместить весь read в try-catch-finally, то переменные с графом вне области видимости дальнейшего кода, более того, могут быть не инициализированы в случае неудачи. Выделять отдельно создание каждого стрима на чтение/запись в try-catch блок тоже невыгодно, потом то надо эти стримы использовать, Более того, я не могу нагуглить, как же быть в такой ситуации - везде разбираются либо случаи без shared data, когда действительно можно разделить на два блока, либо с multiple catch, но одним большим блоком.

2019-11-08 20:28 UTC, SmirnovOleg commented on Task02/Task02/Program.cs
> +                {
А, видимо имелось в виду вынести целиком чтение в отдельный метод, и ловить исключение, которое падает уже из него. Но т.к. этот метод читает и граф, и число вершин, и т.д., то придется либо возвращать целый кортеж всяких данных, либо писать все в поля класса Program, по обращению к которым придется опять же каждый! раз проверять, инициализированы ли они. В общем почему-то мне кажется, что получится много кода, а наглядности и понимания ему это не добавит

2019-11-24 18:33 UTC, EgorkaKulikov commented on Task02/Task02/Edges.cs
> +            return HashCode.Combine(FirstVertex, SecondVertex);
По поводу ответа John Skeet: у меня есть ощущение, что долгое время Решарпер именно так и делал. Вполне возможно, что один из них у другого позаимствовал.

2019-11-24 18:39 UTC, EgorkaKulikov commented on Task02/Task02/ParallelAlgorithms.cs
> +    public static class ParallelAlgorithms
Вопрос статики достаточно сложен на самом деле. Я встречал людей, которые говорят, что статику нужно навешивать почти всюду. Как и ровно противоположный подход: почти нигде. Все эти люди всегда могут привести тысячи аргументов.

В данном случае я написал коммент совершенно не к месту, этот класс действительно статический.

2019-11-24 18:49 UTC, EgorkaKulikov commented on Task02/Task02/Program.cs
> +                {
Я имел в виду скорее следующее:
- есть путь к файлу
- по этому пути мы можем проверить, существует ли файл через File.Exists
- если получает, что его нет, кидаем сами FileNotFoundException и уходим
- в противном случае уже никогда не ожидаем этого исключения

и вот это всё можно было бы вынести в метод, возвращающий File

2019-11-24 18:50 UTC, EgorkaKulikov commented
Я выкладываю PR, если будет желание что-то дообсудить по комментариям, you are welcome!

2019-11-24 18:50 UTC, merged

2019-11-25 08:26 UTC, SmirnovOleg commented on Task02/Task02/Program.cs
> +                {
А, тогда да, просто все равно останется огромный read внутри одного try, и я здесь рассуждал, как бы именно от него избавиться - видимо, никак.