Task05_Privalikhin
EgorkaKulikov/spbu-se2019-autumn pull request #81
Opened 2019-12-05 16:34 UTC by AlekseiPrivalihin

2019-12-15 16:41 UTC, AlekseiPrivalihin commented
Было произведено тестирование на более крупных данных (10 000 добавлений и операций поиска, 5000 удалений)
К сожалению, получившиеся в итоге файлы оказались слишком велики для github
Неизвестным образом, грубая синхронизация работает примерно в 20 раз быстрее тонкой. Первым предположением было то, что поскольку тонкая синхронизация исходно запускалась второй, какое-то время съедал сборщик мусора, но смена порядка показала, что это не так. Timeline профилирование показывает, что грубая синхронизация каким-то чудесным образом работает практически идеально параллельно (чего по идее быть не может, но оно есть). Тонкая же синхронизация, как и положено, сколько-то времени работает, сколько-то времени ждет. Sampling профилирование подтверждает, что это действительно не проблема точности timeline, и вызовы методов тонкой синхронизации работают дольше всего. Текущее предположение в том, что во-первых профилятор неточно отображает работу грубой синхронизации (там вообще нет ожидания, если верить отчету профилятора), а во-вторых в случае с тонкой синхронизацией происходит переполнение тредпула, что сильно тормозит работу

2019-12-15 16:43 UTC, NikitaMishin commented
а чем можно файлы посмотреть? dtt? Райдер может в это?

2019-12-15 16:54 UTC, NikitaMishin commented
не могу в райдере проект собрать, вы все файлы запушили?

2019-12-15 17:13 UTC, NikitaMishin requested changes
Хочетс запустить проект(возможно что-то не то делаю, не находит такую кор версию, а если пересесть на 3.1. то пэкэкджи не находит).Чем файлы посмотреть + замечания-вопросы насчет проверок на нулл после прохождения барьера

2019-12-15 17:13 UTC, NikitaMishin commented on Task05/Task05/CoarseGrainedBST.cs
> +            public int data;
Аналогинчо, есть  правила именования, но здесь не душим за это)

2019-12-15 17:13 UTC, NikitaMishin commented on Task05/Task05/CoarseGrainedBST.cs
> +                    curNode = curNode.right;
а мы здесь к нуллу не можем обратиться вдруг?

2019-12-15 17:13 UTC, NikitaMishin commented on Task05/Task05/CoarseGrainedBST.cs
> +            Node curNode = root;
после того как мы вышли с барьера есть вероятность, что рут== null? Мы могли удалить его, или такое невозможно?

2019-12-15 17:13 UTC, NikitaMishin commented on Task05/Task05/CoarseGrainedBST.cs
> +            mutex.WaitOne();
аналогично, не нужна ли провера на то, что объект уже не удален?если два потока вошли в delete(key), один будет ждать, а другой в это время удалит. Что будет делать второй?

2019-12-15 17:13 UTC, NikitaMishin commented on Task05/Task05/FineGrainedBST.cs
> +            public Mutex mutex;
а замеч на public мьютекс?

2019-12-16 21:40 UTC, NikitaMishin approved these changes

2019-12-16 22:07 UTC, AlekseiPrivalihin commented on Task05/Task05/CoarseGrainedBST.cs
> +                    curNode = curNode.right;
исходно curNode null-ом быть не может, а если curNode.right == null, то все хорошо - мы проходим к условию цикла и выходим из него

2019-12-16 22:08 UTC, AlekseiPrivalihin commented on Task05/Task05/CoarseGrainedBST.cs
> +            Node curNode = root;
Вероятность очень даже есть, но в таком случае мы не зайдем в цикл и дойдем до кода, создающего новый корень
Новый корень в это время появиться не может, потому что дерево залочено

2019-12-16 22:12 UTC, AlekseiPrivalihin commented on Task05/Task05/CoarseGrainedBST.cs
> +            mutex.WaitOne();
второй пройдет по дереву и попытается удалить его еще раз. Если в дереве нет соответствующего ключа, мое удаление просто не делает ничего. Поскольку дерево поддерживает дублирующиеся ключи, в этом нет ничего плохого

2019-12-16 22:12 UTC, AlekseiPrivalihin commented on Task05/Task05/FineGrainedBST.cs
> +            public Mutex mutex;
private его сделать нельзя, поскольку нужен доступ из внешнего класса. Internal, наверно, можно, но поскольку снаружи в любом случае нельзя получить доступ к вершине, находящейся внутри дерева (root приватный), это не влияет на безопасность

2019-12-16 22:18 UTC, merged