Task05_Tsirikov
EgorkaKulikov/spbu-se2019-autumn pull request #83
Opened 2019-12-05 17:12 UTC by Tsirikov

2019-12-15 17:22 UTC, NikitaMishin requested changes
нужны скрипты компиляции, чтобы запустить+ чем открывать результаты профиляции?
А так пока  вроде как все ок, но хотелось бы позапускать.

2019-12-15 17:23 UTC, NikitaMishin commented
А, ну анализ нужен же какой-то, если не ошибаюсь)) Егор ведь просил

2019-12-16 17:52 UTC, Tsirikov commented
Запускать `dotnet test`.
`.dtp` можно открыть через dotTrace или Rider.

2019-12-16 18:06 UTC, EgorkaKulikov commented
Где здесь сравнительный анализ?

2019-12-16 18:29 UTC, Tsirikov commented
Задача сравнить производительность грубой и тонкой синхронизации у обычного BST звучит  странно: тонкая эффективнее грубой, даже на малых деревьях можно видеть разницу в простое на mutex.WaitOne() в отчёте профилятора.

Вопрос мог бы быть нетривиальным для балансирующихся деревьев: для RB-Tree модификация для тонкой синхорнизации хотя и очевидная (удерживать 2 поколения предков для вставки и 3 для удаления), но уже может сказываться на производительности. А вот у АВЛ эффективность удаления с тонкой синхронизацией даже спорна --- балансировки могут потребоваться вплоть до корня, для этой операции может оказаться лучшим вариантом реализовывать грубую.

2019-12-16 18:57 UTC, Tsirikov commented
Ладно, это было слишком заносчиво.

Вы можете предпочесть грубую синхронизацию, если:
1. Обращение к пространству ядра дороже, чем эксклюзивное выполнение операции с деревом. Вообще, это должны быть O(1) и O(log n) соответственно, но константы разные бывают, что вполне можно почувствовать при малых размерах дерева. 
2. Память - критический ресурс, нет места для примитива синхронизации на каждую вершину.

2019-12-16 22:20 UTC, EgorkaKulikov commented
Ну, можно было ещё подумать про latency
Подумать о том, насколько быстрее при малом числе потоков, при очень большом, при "обычном"
Но если не хочется, то ладно.

2019-12-16 22:20 UTC, merged