Duletov_Task05
EgorkaKulikov/spbu-se2019-autumn pull request #84
Opened 2019-12-05 19:54 UTC by Duletov

2019-12-15 17:28 UTC, NikitaMishin commented on Task05/Task05/Program.cs
> +        private Node InerInsert(Node current, Node n)
Inner*

2019-12-15 17:28 UTC, NikitaMishin commented on Task05/Task05/Program.cs
> +        private Node InerInsert(Node current, Node n)
node, наверное, лучше

2019-12-15 17:30 UTC, NikitaMishin commented on Task05/Task05/Program.cs
> +                current = balance_tree(current);
underscore в си шарпе у метода? Ну ладно

2019-12-15 17:33 UTC, NikitaMishin requested changes
пока на первый взгляд все норм,
по структуре нехорошо, почему все в одном файле?
и где результаты профиляции и анализ  полученных результатов?

2019-12-15 18:42 UTC, Duletov commented
Очень хотелось выложить 6 задачу в срок (успел), так что разработка 5 была приостановлена. Скоро выложу ещё тестов и отчёты профилятора. Пока что вот фиксы по комментам.

2019-12-15 19:14 UTC, NikitaMishin commented
ок, как доделаете, отпишитесь или менш сделайте

2019-12-15 23:12 UTC, Duletov commented
Переделал много чего в коде в соответствие с советами профилятора. Принципиальных изменений почти нет. В основном правил код стайл и в паре мест убрал недостижимый код. Добавил мои наблюдения почерпнутые после профилирования, думаю это будет понятней, чем какие-то скриншоты. Если надо ещё чего-то приложить, готов вкалывать)

2019-12-17 17:01 UTC, Duletov commented
> ок, как доделаете, отпишитесь или менш сделайте

2019-12-17 17:56 UTC, NikitaMishin commented on Task05/Task05/LazyAVL.cs
> +        public void RealDelete()
такое название пользователю мозг вынесет:), учитывая, что есть Delete()

2019-12-17 17:58 UTC, NikitaMishin approved these changes

2019-12-17 18:04 UTC, Duletov commented on Task05/Task05/LazyAVL.cs
> +        public void RealDelete()
Чисто в теория функция не пользовательская, а серверная и запускается условно раз в день автоматом. Но название не очень отражает смысл, согласен. Возможно, CleanTree какой-нибудь подошёл бы лучше. Но вообще я не знаю, как это правильно назвать

2019-12-17 21:17 UTC, merged