Task05_Abzalov
EgorkaKulikov/spbu-se2019-autumn pull request #89
Opened 2019-12-07 17:29 UTC by viabzalov

## Реализовано
* Потокобезопасное наивное двоичное дерево поиска c операциями `Find` и `Insert`
  * С грубым `Coarse-grained` подходом синхронизации
  * С тонким `Fine-grained` подходом синхронизации
* Юнит-тестирование с помощью [NUnit](https://nunit.org/)
* Профилирование с помощью [dotTrace](https://www.jetbrains.com/profiler/)

2019-12-16 20:09 UTC, skoret requested changes
- [ ] проект наверняка писался в visual studio или raider'е, поэтому, пожалуйста, залейте в репозиторий все необходимые файлы для безболезненной сборки кода локально: .sln, .csproj

на комменты к исправленным замечаниям стоит отвечать и прокликивать чекбоксы, чтобы успростить жизнь ревьюеру и скорее получить фидбек

2019-12-16 20:09 UTC, skoret commented on Concurrent trees/Coarse/Tree.cs
> +        private readonly Node fakeRoot = new Node();
`fakeRoot` действительно необходим?
похоже, что к нему привязывается настоящий корень, но больше обращений к нему нет

2019-12-16 20:09 UTC, skoret commented on Concurrent trees/Coarse/Tree.cs
> +                if (node.Key > key)
нано-придирка на будущее:
синтаксически такая конструкция корректна
и с точки зрения читабельности тоже вроде всё ок
но чаще всё же стоит ожидать, что в будущем ваш код будет поддерживать и обновлять кто-то другой
конкретно в этом случае, как мне кажется, некоторая часть людей не заметит отсутствия фигурных скобок, допишет какую-либо логику после `if (...) {...} else {...}` и будет думать, что его код будет исполняться в вашем цикле

2019-12-16 20:09 UTC, skoret commented on Concurrent trees/Coarse/Tree.cs
> +        private readonly Mutex _mutex = new Mutex();
в чём преимущество использования мьютекса перед конструкцией `lock (<object>) {...}` для грубой синхронизации?
выглядит так, что поведение будет абсолютно аналогичным
плюс: `lock` отпустится, когда мы выйдем из его тела, даже если внутри где-то вылезет эксепшн, в отличие от вашего решения

- [ ] придумать (подсмотреть у одногруппников), как отпускать мьютекс **всегда**, либо рассмотреть возможность переехать на `lock`

2019-12-16 20:09 UTC, skoret commented on Concurrent trees/Fine/Tree.cs
> +                node = next;
похоже, что при некоторых кейсах попытка отпустить мьютекс на родителе может приводить к `ApplicationException`
например:
на строчке [#32](https://github.com/EgorkaKulikov/spbu-se2019-autumn/pull/89/files?file-filters%5B%5D=.cs#diff-570211f46ca7fc4ed772d32ecbd436b9R32) в `next` записывается ребёнок текущего узла
между строками [#32](https://github.com/EgorkaKulikov/spbu-se2019-autumn/pull/89/files?file-filters%5B%5D=.cs#diff-570211f46ca7fc4ed772d32ecbd436b9R32) и [#42](https://github.com/EgorkaKulikov/spbu-se2019-autumn/pull/89/files?file-filters%5B%5D=.cs#diff-570211f46ca7fc4ed772d32ecbd436b9R42) в теории может пройти вечность, в которой наверняка будет что-то такое `next.Parent = new Node(key)` или даже затирание нуллом
далее мы повторяем `while`, доходим до строчки [#27](https://github.com/EgorkaKulikov/spbu-se2019-autumn/pull/89/files?file-filters%5B%5D=.cs#diff-570211f46ca7fc4ed772d32ecbd436b9R27), где пытаемся отпустить лок с родителя
а родитель, увы, уже по факту новый

- [ ]  возможно, стоит лочить ребёнка прежде, чем брать его // возможно, есть другое решение

2019-12-16 20:09 UTC, skoret commented on Concurrent trees/Fine/Tree.cs
> +                node = next;
к слову, в функции `Insert` этот кейс выглядит обработанным и отрабатывающим корректно

2019-12-17 15:28 UTC, viabzalov commented on Concurrent trees/Coarse/Tree.cs
> +        private readonly Node fakeRoot = new Node();
Согласен. С помощью `lock(this)` `fakeRoot` можно упразднить.

2019-12-17 15:30 UTC, viabzalov commented on Concurrent trees/Coarse/Tree.cs
> +                if (node.Key > key)
Согласен, но, к сожалению, эти скобки удаляет Code Cleanup в Rider'е. Может это как-то можно отключить?

2019-12-17 15:31 UTC, viabzalov commented on Concurrent trees/Coarse/Tree.cs
> +        private readonly Mutex _mutex = new Mutex();
В данном случае преимущест `Mutex` над `lock (<object>)` не вижу. Код исправил.

2019-12-17 15:35 UTC, viabzalov commented on Concurrent trees/Fine/Tree.cs
> +                node = next;
Такого, конечно, не могло быть, поскольку внутри цикла поддерживается инвариантность исключительности доступа к текущей вершине и к её предку. Так же, поскольку дерево пишется без удаления, проблем с обращением по ссылкам не возникает.

2019-12-17 15:41 UTC, viabzalov commented
* Пересмотрел концепцию применения `Mutex` вместо `lock (<object>)` и переписал решение на основе `lock`'ов. 
  * Стоит отметить, что, поскольку дерево написано без удаления, применение `lock`'ов делает код более лаконичным и каноничным.
* Тесты всё так же 100%
* Заменил файлы профилятора на `Timeline Profiling`.
* Отдельный исследовательский интерес представляет реализация с удалением, но, это не является целью настоящей работы.

2019-12-17 21:18 UTC, merged