Task05_Kanashin
EgorkaKulikov/spbu-se2019-autumn pull request #92
Opened 2019-12-07 20:51 UTC by KanashinDmitry

2019-12-15 18:33 UTC, KanashinDmitry commented
Реализованы грубая и тонкая синхронизации бинарного дерева (вставка, поиск, удаление).
При удалении меняется значение, если существует правое поддерево у левого сына или левое поддерево у правого сына удаляемой вершины, иначе происходит изменение ссылок.
Написаны unit-тесты для покрытия основных сценариев при последовательном исполнении операций.
В качестве тестов на сценарии с параллельным исполнением операций были выбраны параллельные вставка/поиск/удаление, вставка/поиск, поиск/удаление. Случаи, когда параллельно запускаются операции без какого-либо time-delay не рассматриваются, так как при разных запусках тестов поведение не будет повторяемым. Операции запускались параллельно с помощью Task'ов. Вся проверка корректной работы сводилась к выполнению свойства бинарного дерева и проверки на предполагаемое содержимое дерева.
В отчете профилятора видно, что только на одном тесте есть заметное ускорение работы операций у тонкой синхронизации в отношении к грубой. В остальных же время работы примерно одинаковое.

2019-12-15 20:32 UTC, skoret requested changes
похоже, что это распространённая проблема сейчас, но всё же
пожалуйста, заливайте в репозиторий вне необходимые файлы для сборки проекта
особенно .sln

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/BinaryTree.cs
> +        protected Node CreateNode(K key, V value, Node parent)
protected метод для создания узла правда необходим?
чем не угодил конструктор?

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/CoarseGrainedBinaryTree.cs
> +            var isDeeperRight = rightD?.LeftSon switch
простое сравнение `!= null` не даст тот же результат?

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +            Mutex rootMutex = new Mutex();
идея благая — не дать двум потокам в одно и то же время сеттить корень
но при каждом вызове `Insert` будет создаваться отдельный объект мьютекса для каждого вызвавшего потока
а для синхронизации разные потоки должны использовать один и тот же объект

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                            currNode.RightSon?.Mtx.WaitOne();
похоже на лишнюю проверку на null, т.к. если правого сына не было выше, то мы сюда не дойдём
аналогично в `case: -1`

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +            var rootMutex = new Mutex();
та же тема с отдельным инстансом мьютекса, который по-хорошему должен быть один для всех тредов

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/CoarseGrainedBinaryTree.cs
> +        private readonly Mutex _mutex = new Mutex();
в чём выгода здесь использовать именно мьютекс, а не `lock` на объекте?

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +            var isDeeperRight = rightD?.LeftSon switch
аналогично `!= null` будет читаться куда проще

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                        parent?.ChangeSon(isCurrLeftSon, rightS);
не нужно здесь и далее лочиться на родителе?

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                leftD.RightSon?.Mtx.WaitOne();
если мы зашли в while, по `.?` явно лишние

2019-12-15 20:32 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                rightD.Parent.ChangeSon(true, rightD.RightSon);
не нужно здесь лочиться на родителя и правого сына?

2019-12-16 06:56 UTC, skoret requested changes
- [x] залить .sln файл
- [x] лочиться на одном объекте между тредами, а не создавать новый для каждого

2019-12-16 20:08 UTC, skoret commented
на комменты к исправленным замечаним, пожалуйста, пишите ответ, либо прокликивайте чекбоксы
так намного удобнее оставаться в синхронизации и, соответственно, фидбек придёк куда быстрее

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                rightD.Parent.ChangeSon(true, rightD.RightSon);
Здесь лочиться на родителе не нужно, так как удалить родителя не смогут удалить, т.к. мы лочим удаляемую, и по тем, что спускаемся, а когда спустились, сверху на родителе никто лок не держит, на сыне, если всё же какой-то поток захотел удалить родителя, то он либо удалит его еще до того, как текущий поток сможет залочить его при спуске, либо после, когда мы снимем лок с удаляемой вершины. Насчет сына действительно надо лочиться, т.к. его может удалить другой поток, который спустился раньше (для симметричного случая тоже исправил).

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                leftD.RightSon?.Mtx.WaitOne();
Исправил

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                        parent?.ChangeSon(isCurrLeftSon, rightS);
В данном случае да, нужно, исправил

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +            var isDeeperRight = rightD?.LeftSon switch
Исправлено

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +            var rootMutex = new Mutex();
Исправлено

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                            currNode.RightSon?.Mtx.WaitOne();
Исправлено

2019-12-16 20:48 UTC, KanashinDmitry commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +            Mutex rootMutex = new Mutex();
Исправил

2019-12-16 20:49 UTC, KanashinDmitry commented on Task05/Parallel_Trees/CoarseGrainedBinaryTree.cs
> +            var isDeeperRight = rightD?.LeftSon switch
Да, просто когда писал код, не обратил внимание, что это одно и то же)

2019-12-16 20:49 UTC, KanashinDmitry commented on Task05/Parallel_Trees/BinaryTree.cs
> +        protected Node CreateNode(K key, V value, Node parent)
Действительно, убрал этот метод

2019-12-16 20:49 UTC, KanashinDmitry commented on Task05/Parallel_Trees/CoarseGrainedBinaryTree.cs
> +        private readonly Mutex _mutex = new Mutex();
Разницы особой нет в данной задаче, скорее для однообразия синхронизации

2019-12-16 20:55 UTC, KanashinDmitry commented
То, как прокликивать чекбоксы, не совсем понял, но 
- .sln файл добавлен
- ошибку с локами между тредами на корне исправил

2019-12-16 21:27 UTC, skoret commented on Task05/Parallel_Trees/FineGrainedBinaryTree.cs
> +                leftD.RightSon?.Mtx.WaitOne();
похоже, не исправил, хех

2019-12-16 21:28 UTC, skoret commented
> То, как прокликивать чекбоксы, не совсем понял, но

ох, я думал, что можно в чужих комментах их прокликивать
прошу прощения, привычка от битбакета

вродь всё чик-чирик

2019-12-16 21:29 UTC, skoret approved these changes
👌🏻

2019-12-16 22:22 UTC, merged